name: build resume
on: [push]

jobs:
  resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex

      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
